### ISSUE TITLE
Change default Booleans to False

### ISSUE THREAD

**Issue by Yamakasi** [theforeman/puppet-foreman_proxy#342]
I think it's better to set most booleans to false when you look at CA, Puppet, etc.

De default parameters are far from ideal to start with that I think it's better to set them all to false in params.pp.

**Comment by domcleal** [comment]
For future reference, which boolean(s) precisely should be set to false?

**Comment by Yamakasi** [comment]
Once I fugured out what is needed for #343 I can add some extra information about it on global usage, but to start with:

dns_managed => false (when you enable dns you don't want to have it default managed)
dhcpd_managed => false (depends on #343 but as you need dhcp for PXE boot you will have dhcp=> true)
puppetca => true ; why ? most puppet CA's are on foreman by default and need to be installed once anyways (if not loadbalancing)

Maybe I need to create some "best start params.pp" as PR when I figured out #343

**Comment by ekohl** [comment]
I don't think switching those _managed booleans makes sense and I like our current defaults there. puppetca maybe but if you are doing ha/load balancing then you need to do a lot more and look at a lot more parameters. I'm open to changing something but closing this now. I think a discussion on foreman-dev is the best way to figure out what would be best because it's much more visible to users than an issue here.
